{"name": "用户确认登陆 验证码错误", "status": "passed", "steps": [{"name": "用户请求登陆", "status": "passed", "start": 1673432978249, "stop": 1673432978936}, {"name": "用户确认连接", "status": "passed", "start": 1673432978936, "stop": 1673432979270}], "attachments": [{"name": "log", "source": "3cbac14e-0bb2-4e65-8de4-8ac988534ff3-attachment.txt", "type": "text/plain"}], "parameters": [{"name": "test_title", "value": "'用户确认登陆 验证码错误'"}, {"name": "email", "value": "'15873664024@163.com'"}, {"name": "oneTimePassword", "value": "'123456'"}, {"name": "status_code", "value": "400"}, {"name": "code", "value": "2100000"}], "start": 1673432978249, "stop": 1673432979270, "uuid": "f2761188-ce89-40b2-8571-8ace2f825b4e", "historyId": "83298246784b3c29071eb97ec6155d7d", "testCaseId": "8ceef3418acc8d9fb84fa541b73aaf3a", "fullName": "Testcase.Test_User.test_uesr_confirm_fail.Test_create_custodial_account#test_create_account_custodial", "labels": [{"name": "story", "value": "User Connect Fail!"}, {"name": "feature", "value": "Users Fail!"}, {"name": "parentSuite", "value": "Testcase.Test_User"}, {"name": "suite", "value": "test_uesr_confirm_fail"}, {"name": "subSuite", "value": "Test_create_custodial_account"}, {"name": "host", "value": "lilongdeMacBook-Pro.local"}, {"name": "thread", "value": "2658-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "Testcase.Test_User.test_uesr_confirm_fail"}]}