{"name": "用户请求登陆 邮箱格式异常", "status": "passed", "steps": [{"name": "用户请求登陆", "status": "passed", "start": 1673433075311, "stop": 1673433076167}], "attachments": [{"name": "log", "source": "7e48bd63-c28a-4739-a7a9-92e804e8d841-attachment.txt", "type": "text/plain"}], "parameters": [{"name": "test_title", "value": "'用户请求登陆 邮箱格式异常'"}, {"name": "email", "value": "'15873664023'"}, {"name": "status_code", "value": "400"}, {"name": "code", "value": "2100000"}], "start": 1673433075311, "stop": 1673433076167, "uuid": "e77d205f-f21e-4fd1-b895-b1a6d1681682", "historyId": "a50a42ab7fe717fccc6e33424d973885", "testCaseId": "9aa8d67640221a5991a83be135c3215d", "fullName": "Testcase.Test_User.test_user_req_fail.Test_create_custodial_account#test_create_account_custodial", "labels": [{"name": "feature", "value": "Users Fail!"}, {"name": "story", "value": "User Connect Fail!"}, {"name": "parentSuite", "value": "Testcase.Test_User"}, {"name": "suite", "value": "test_user_req_fail"}, {"name": "subSuite", "value": "Test_create_custodial_account"}, {"name": "host", "value": "lilongdeMacBook-Pro.local"}, {"name": "thread", "value": "2687-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "Testcase.Test_User.test_user_req_fail"}]}